### ISSUE TITLE
Local variable in attribute does not seem to work

### ISSUE THREAD

**Issue by bergwerf** [dartist/jaded#6]
This is my template
```
doctype html
html
  head
    title= title
    link(
      rel="stylesheet",
      href=bootstrap.src,
      integrity=bootstrap.sha
      crossorigin="anonymous")
```

The rendered Dart template is incorrect for two reasons. First of all it doesn't make a reference to bootstrap (which is uses to put bootstrap in the HTML string. And secondly it puts `bootstrap.src` in the Dart code which I think should rather be `bootstrap['src']`.

Another remark, when rendering the string I think it would be better to add the separate parts to the buffer in separate `add` calls instead of having just one add and appending strings using the append operator. This is just as inefficient as using no buffer at all (I might be wrong, but I believe strings are read-only, so it will create a lot of in-memory copies, you should rather use string interpolation or a `StringBuffer`).

**Comment by hermanbergwerf** [comment]
I hope this can be fixed, I'm already addicted to Jade ;-).

**Comment by mythz** [comment]
FYI I don't believe anyone is maintaining this repo anymore so it's unlikely there's anyone available to resolve any issues reported here.

> This is just as inefficient as using no buffer at all (I might be wrong, but I believe strings are read-only, so it will create a lot of in-memory copies, you should rather use string interpolation or a StringBuffer).

Don't assume anything wrt JavaScript performance, you always need to validate your assumptions by either finding an existing benchmark or doing some micro benchmarks yourself. e.g. [String concatenation is faster in JavaScript](https://jsperf.com/join-concat/2). Any JS performance advice you give others should be tested and validated or at least attributed. [JS Perf](https://jsperf.com/) is a good place to create/run micro benchmarks.

**Comment by hermanbergwerf** [comment]
I see.
In this case I want to use it as a server side program (to pre render) so
it's actually about DartVM performance. But you have a fair point.

I'm considering building a nodejs server in between to take care of
template rendering.

**Comment by cheney-enterprises** [comment]
This appears to have been addressed. Please reopen a new issue if you have further concerns.
